version: "3.4"
services:
  code:
    image:
      {{name}}_code
    volumes:
      - ./app:/app
    ports:
      - "2222:22"
    restart: always
  dev:
    image:
      {{name}}_dev
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    restart: always
{{#features.jupyter}}
  jupyter:
    image:
      {{name}}_jupyter
    volumes:
      - ./app:/app
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"
    restart: always
{{/features.jupyter}}
